# Generated by Django 4.1.7 on 2023-03-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SSE', 'Senior Software Engineer'), ('JSE', 'Junior Software Engineer'), ('T', 'Tester')], max_length=255),
        ),
    ]
