# Generated by Django 4.1.7 on 2023-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcapp', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SSE', 'Senior Software Engineer'), ('JSE', 'Junior Software Engineer')], max_length=255),
        ),
    ]
