# Generated by Django 4.1.7 on 2023-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcapp', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(choices=[('P', 'PUNE'), ('B', 'BANGALORE'), ('C', 'CHENNAI')], max_length=255),
        ),
    ]
