# Generated by Django 4.1.7 on 2023-03-14 21:09

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.person')),
                ('eid', models.IntegerField(unique=True)),
                ('salary', models.FloatField()),
                ('role', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Employee',
            },
            bases=('inventory.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.person')),
                ('sid', models.IntegerField(default=1)),
                ('sdept', models.CharField(max_length=20)),
                ('scourse', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Student',
            },
            bases=('inventory.person',),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('empref', models.ManyToManyField(to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('empref', models.ForeignKey(on_delete=models.SET(inventory.models.my_logic), to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('empref', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='inventory.employee')),
            ],
        ),
    ]
