# Generated by Django 4.1.7 on 2023-03-08 15:39

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='empref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='empref',
            field=models.ForeignKey(on_delete=models.SET(inventory.models.my_logic), to='inventory.employee'),
        ),
    ]
