# Generated by Django 4.1.7 on 2023-03-09 18:38

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_address_empref_alter_roles_empref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='empref',
            field=models.OneToOneField(on_delete=models.SET(inventory.models.my_logic), to='inventory.employee'),
        ),
    ]
